"""Keep a relabelling job moving across free GPU providers without babysitting it.

    submit  upload job.json and the prepared input set to the hub
    status  show teachers done, workers alive and recent launches
    tick    one scheduling step; run it from cron (see .github/workflows/gpu-orchestrator.yml)

On each tick: if the job is finished or a worker sent a heartbeat recently, do nothing.
Otherwise take providers in --providers order. Kaggle is started through the official
Kaggle API (`kaggle kernels push`). A provider that was launched but never produced a
heartbeat, typically because its weekly GPU quota is used up, is skipped for --backoff-hours.
Colab has no launch API, so for Colab the tick opens a GitHub issue with a one-click
notebook link and waits for someone to press Run all.

Use one account per provider and stay within each provider's terms: this spreads one job
over the free quotas you have, it does not work around them.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import time
import urllib.request

SCRIPTS = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPTS))

from gpu_hub import open_hub  # noqa: E402

STALE_MINUTES = 25.0   # heartbeats come every 10 minutes; three missed means the worker is gone
GRACE_MINUTES = 45.0   # time a fresh launch gets to install vLLM and send its first heartbeat
ISSUE_TITLE = "Anarkali GPU job needs a Colab run: {job}"


def job_status(hub, job: str) -> dict:
    prefix = f"jobs/{job}"
    files = hub.list(prefix)
    if f"{prefix}/job.json" not in files:
        raise SystemExit(f"no job {job!r} in the hub; run `submit` first")
    heartbeats = [hub.read_json(f) for f in files if f.startswith(f"{prefix}/heartbeat/")]
    launches = {Path(f).stem: hub.read_json(f) for f in files if f.startswith(f"{prefix}/launches/")}
    return {
        "teachers": [t["name"] for t in hub.read_json(f"{prefix}/job.json")["teachers"]],
        "done": sorted(Path(f).stem for f in files if f.startswith(f"{prefix}/done/")),
        "finished": f"{prefix}/output/manifest.json" in files,
        "heartbeats": [h for h in heartbeats if h],
        "launches": {k: v for k, v in launches.items() if v},
        "cache_shards": sum(1 for f in files if f.startswith(f"{prefix}/cache/")),
    }


def decide(status: dict, providers: list[str], now: float, backoff_hours: float,
           stale_minutes: float = STALE_MINUTES, grace_minutes: float = GRACE_MINUTES) -> tuple[str, str | None]:
    """Pure scheduling rule: ('done'|'running'|'waiting'|'launch'|'stalled', detail)."""
    if status["finished"]:
        return "done", None
    for beat in status["heartbeats"]:
        if not beat.get("final") and now - beat["time"] < stale_minutes * 60:
            return "running", beat["worker"]
    for provider in providers:
        launch = status["launches"].get(provider)
        if launch is None:
            return "launch", provider
        age = now - launch["time"]
        if launch.get("failed"):
            if age >= backoff_hours * 3600:
                return "launch", provider
            continue
        if age < grace_minutes * 60:
            return "waiting", provider
        answered = any(b.get("provider") == provider and b["time"] >= launch["time"] for b in status["heartbeats"])
        if answered or age >= backoff_hours * 3600:
            return "launch", provider
    return "stalled", None


def kaggle_kernel_dir(root: Path, *, username: str, hub: str, job: str, repo_url: str, ref: str,
                      hours: float, accelerator: str = "NvidiaTeslaT4") -> Path:
    root.mkdir(parents=True, exist_ok=True)
    (root / "kernel-metadata.json").write_text(json.dumps({
        "id": f"{username}/anarkali-gpu-worker", "title": "anarkali-gpu-worker",
        "code_file": "run.py", "language": "python", "kernel_type": "script",
        "is_private": True, "enable_gpu": True, "enable_internet": True, "machine_shape": accelerator,
        "dataset_sources": [], "competition_sources": [], "kernel_sources": [], "model_sources": [],
    }, indent=2) + "\n", encoding="utf-8")
    (root / "run.py").write_text(f'''# Generated by scripts/gpu_orchestrator.py. Attach a Kaggle secret named HF_TOKEN once.
import os, subprocess, sys
from kaggle_secrets import UserSecretsClient
os.environ["HF_TOKEN"] = UserSecretsClient().get_secret("HF_TOKEN")
subprocess.check_call(["git", "clone", "--depth", "1", "--branch", {ref!r}, {repo_url!r}, "anarkali"])
subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "vllm", "huggingface_hub"])
subprocess.check_call([sys.executable, "anarkali/scripts/gpu_worker.py", "--hub", {hub!r}, "--job", {job!r},
                       "--provider", "kaggle", "--max-hours", {str(hours)!r}])
''', encoding="utf-8")
    return root


def kaggle_gpu_hours_left() -> float | None:
    """Remaining weekly Kaggle GPU hours, or None when this kaggle client cannot tell."""
    try:
        from kaggle.api.kaggle_api_extended import KaggleApi
        api = KaggleApi()
        api.authenticate()
        quota = api.quota_view().gpu_quota
        return (quota.total_time_allowed - quota.time_used).total_seconds() / 3600
    except Exception:
        return None


def launch_kaggle(args) -> str:
    username = os.environ.get("KAGGLE_USERNAME")
    if not username or not os.environ.get("KAGGLE_KEY"):
        raise RuntimeError("KAGGLE_USERNAME and KAGGLE_KEY must be set to launch on Kaggle")
    hours = args.kaggle_hours
    left = kaggle_gpu_hours_left()
    if left is not None:
        if left < 1.0:
            raise RuntimeError(f"Kaggle GPU quota has {left:.1f} h left this week")
        hours = min(hours, left - 0.5)
    with tempfile.TemporaryDirectory() as tmp:
        kernel = kaggle_kernel_dir(Path(tmp), username=username, hub=args.hub, job=args.job,
                                   repo_url=args.repo_url, ref=args.ref, hours=round(hours, 2),
                                   accelerator=args.kaggle_accelerator)
        result = subprocess.run(["kaggle", "kernels", "push", "-p", str(kernel)], capture_output=True, text=True)
    output = (result.stdout + result.stderr).strip()
    if result.returncode != 0:
        raise RuntimeError(f"kaggle kernels push failed: {output}")
    return output


def colab_link(repo_url: str, ref: str) -> str:
    slug = repo_url.removeprefix("https://github.com/").removesuffix(".git")
    return f"https://colab.research.google.com/github/{slug}/blob/{ref}/notebooks/gpu_worker_colab.ipynb"


def github_request(method: str, path: str, payload: dict | None = None):
    token, repo = os.environ.get("GITHUB_TOKEN"), os.environ.get("GITHUB_REPOSITORY")
    if not token or not repo:
        return None
    request = urllib.request.Request(
        f"https://api.github.com/repos/{repo}{path}", method=method,
        data=None if payload is None else json.dumps(payload).encode("utf-8"),
        headers={"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json"})
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.loads(response.read().decode("utf-8"))


def launch_colab(args) -> str:
    link = colab_link(args.repo_url, args.ref)
    title = ISSUE_TITLE.format(job=args.job)
    body = (f"Every automatic provider is out of free GPU time for job `{args.job}`.\n\n"
            f"1. Open [the worker notebook in Colab]({link}) and pick a GPU runtime.\n"
            f"2. Add a Colab secret `HF_TOKEN`, set `HUB` to `{args.hub}` and `JOB` to `{args.job}`.\n"
            f"3. Press **Run all**. The job continues from the shared cache and this issue can be closed.\n")
    open_issues = github_request("GET", "/issues?state=open&per_page=100")
    if open_issues is None:
        return f"no GitHub token; open this notebook yourself: {link}"
    if any(issue.get("title") == title for issue in open_issues):
        return "Colab issue already open"
    issue = github_request("POST", "/issues", {"title": title, "body": body})
    return f"opened {issue.get('html_url')}"


LAUNCHERS = {"kaggle": launch_kaggle, "colab": launch_colab}


def submit(args):
    hub = open_hub(args.hub)
    job = json.loads(Path(args.config).read_text(encoding="utf-8"))
    if not job.get("teachers") or len({t["name"] for t in job["teachers"]}) != len(job["teachers"]):
        raise SystemExit("job config needs teachers with unique names")
    for teacher in job["teachers"]:
        if not teacher.get("model"):
            raise SystemExit(f"teacher {teacher.get('name')!r} has no model")
    for name in ("manifest.json", "train.jsonl", "development.jsonl", "calibration.jsonl", "test.jsonl"):
        if not (Path(args.input) / name).exists():
            raise SystemExit(f"{args.input} is missing {name}")
    hub.push_folder(Path(args.input), f"jobs/{args.job}/input")
    hub.write_json(f"jobs/{args.job}/job.json", job)
    print(f"submitted jobs/{args.job} to {args.hub}")


def tick(args) -> tuple[str, str | None]:
    hub = open_hub(args.hub)
    providers = [p.strip() for p in args.providers.split(",") if p.strip()]
    unknown = set(providers) - set(LAUNCHERS)
    if unknown:
        raise SystemExit(f"unknown providers: {', '.join(sorted(unknown))}")
    status = job_status(hub, args.job)
    for _ in providers:  # a failed launch falls through to the next provider in the same tick
        now = time.time()
        action, detail = decide(status, providers, now, args.backoff_hours)
        if action != "launch":
            break
        record = {"provider": detail, "time": now}
        try:
            record["message"] = LAUNCHERS[detail](args)
        except Exception as exc:
            # recorded, so a provider out of quota is backed off instead of retried every tick
            record.update(message=f"launch failed: {exc}", failed=True)
        hub.write_json(f"jobs/{args.job}/launches/{detail}.json", record)
        status["launches"][detail] = record
        print(f"launch {detail}: {record['message']}")
        if not record.get("failed"):
            return action, detail
    if action == "launch":  # every provider failed this tick
        action, detail = decide(status, providers, time.time(), args.backoff_hours)
    print(f"{action}{'' if detail is None else ': ' + detail}")
    return action, detail


def main(argv: list[str] | None = None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--hub", required=True, help="hf:owner/repo or a shared directory")
    parser.add_argument("--job", required=True)
    sub = parser.add_subparsers(dest="command", required=True)
    p_submit = sub.add_parser("submit")
    p_submit.add_argument("--config", required=True, help="job.json with teachers, splits and relabel_args")
    p_submit.add_argument("--input", required=True, help="prepared decision directory")
    sub.add_parser("status")
    p_tick = sub.add_parser("tick")
    p_tick.add_argument("--providers", default="kaggle,colab")
    p_tick.add_argument("--backoff-hours", type=float, default=24.0)
    p_tick.add_argument("--kaggle-hours", type=float, default=8.0, help="worker time budget on Kaggle")
    p_tick.add_argument("--kaggle-accelerator", default="NvidiaTeslaT4",
                        help="Kaggle machine_shape; vLLM needs a T4 or newer, not the P100")
    default_repo = f"https://github.com/{os.environ['GITHUB_REPOSITORY']}" if os.environ.get("GITHUB_REPOSITORY") \
        else "https://github.com/ToufiqQureshi/anarkali"
    p_tick.add_argument("--repo-url", default=default_repo)
    p_tick.add_argument("--ref", default="main", help="branch the workers clone")
    args = parser.parse_args(argv)
    if args.command == "submit":
        return submit(args)
    if args.command == "status":
        status = job_status(open_hub(args.hub), args.job)
        print(json.dumps(status, indent=2))
        return status
    return tick(args)


if __name__ == "__main__":
    main()
